
name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build and push docker image
        uses: jerray/publish-docker-action@master
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.actor }}/zz-shop/zz-shop
          auto_tag: true